Add Chessboard
pesto-students/batch-6-chess-multiplayer pull request #18
Opened 2019-04-24 20:07 UTC by codemayank

Adds Component to render the chess board.
resolves #15

2019-04-24 22:17 UTC, nimish-gupta requested changes
Please add tests for this PR.
Also, setup eslint/husky if not done and then rebase this PR on top of that.
Also, add the screen shots for the visual changes

2019-04-24 22:17 UTC, nimish-gupta commented on client/src/App.js
>    constructor(props) {
use class variables here.

2019-04-24 22:17 UTC, nimish-gupta commented on client/src/App.js
>            {' '}
Why this space?

2019-04-24 22:17 UTC, nimish-gupta commented on client/src/components/chessboard/chessboard.js
> +    <div role="button" tabIndex={0} onKeyPress={handleClick} onClick={handleClick} grid-position={gridPosition} className={isDark ? 'dark-square' : 'light-square'} />
Have you guys setup husky/eslint?

2019-04-24 22:17 UTC, nimish-gupta commented on client/src/components/chessboard/chessboard.js
> +const squares = chess.SQUARES;
Comment out here the type of squares so that the user can know what squares consist of.

2019-04-24 22:17 UTC, nimish-gupta commented on client/src/components/chessboard/chessboard.js
> +const generateGrid = (playerColor) => {
Can you right test for this one?

2019-04-24 22:19 UTC, Prabhakar-Poudel commented on client/src/components/chessboard/chessboard.js
> +    <div role="button" tabIndex={0} onKeyPress={handleClick} onClick={handleClick} grid-position={gridPosition} className={isDark ? 'dark-square' : 'light-square'} />
We have. It is in master.

2019-04-26 17:16 UTC, codemayank commented
We have restructured the client app and this component will have to be written again so ill have to close this pr.
@nimish-gupta

2019-04-29 00:42 UTC, closed without merging