Implement timer component
pesto-students/batch-6-chess-multiplayer pull request #19
Opened 2019-04-24 22:04 UTC by Prabhakar-Poudel

Closes: #17

2019-04-24 22:22 UTC, nimish-gupta requested changes
Rebase this branch before merging.
Add screenshots to visual changes

2019-04-24 22:22 UTC, nimish-gupta commented on client/src/components/timer/Timer.jsx
> +  render() {
It can be a functional component, if you are not using any state

2019-04-24 22:22 UTC, nimish-gupta commented on client/src/utils/timerUtil.test.js
> +  // TODO: test negative cases after test framework is integrated.
Please handle all the cases here in this PR only, as todos will get lined up very easily. Try to avoid that.

2019-04-30 12:26 UTC, Prabhakar-Poudel commented
@nimish-gupta 
Closing this as this component already exist
And in favor of 
#27

2019-04-30 12:26 UTC, closed without merging