generate jwt
pesto-students/batch-6-chess-multiplayer pull request #62
Opened 2019-05-06 00:58 UTC by chirag-shinde

fixes #58 and solves #28 

- Return a jwt from the server on successful login
- Implement a middleware to check jwt is present in the request header to access protected routes.
- Save jwt to localstorage on the client side.

2019-05-06 01:05 UTC, nimish-gupta approved these changes

2019-05-06 01:05 UTC, nimish-gupta commented on server/src/controllers/auth.js
>    };
Checkuser is not always returning userid.

2019-05-06 03:33 UTC, Prabhakar-Poudel requested changes

2019-05-06 03:33 UTC, Prabhakar-Poudel commented on client/src/auth/auth.js
> +    localStorage.removeItem('jwt'); // placeholder till JWT generation is built.
Please remove outdated comments.

2019-05-06 03:33 UTC, Prabhakar-Poudel commented on client/src/components/dashboard/Dashboard.js
> +    axios.get(process.env.REACT_APP_DASHBOARD_URL, {
may be we need a networking layer that parsees tokens/data, and gives component the data it neds. A component fiddling with headers is not a great idea.

2019-05-06 03:33 UTC, Prabhakar-Poudel commented on client/src/components/dashboard/Dashboard.js
> +        'x-auth-token': localStorage.getItem('jwt'),
We also need a layer to get data from. Although localstorage is accessible to all components, a fine layer of abstraction is always better, you can even build a HOC that passes this component required data. But it's not big of a deal now.

2019-05-06 03:33 UTC, Prabhakar-Poudel commented on client/src/components/dashboard/Dashboard.js
> +        onClick={() => {
This doesn't look very linear, see if you can refactor.

2019-05-06 03:33 UTC, Prabhakar-Poudel commented on client/src/components/dashboard/Dashboard.js
> +  Logout
The indentation here.

2019-05-06 03:33 UTC, Prabhakar-Poudel commented on client/src/components/routes/ProtectedRoute.js
> +      render={props => (auth.isAuthenticated() ? (
This too looks a bit non leaner. See if it can be refactored.

2019-05-06 03:33 UTC, Prabhakar-Poudel commented on server/package.json
> +    "jsonwebtoken": "^8.5.1"
All other dependencies are following alphabetical order. Some plugin automatically does this for you.

2019-05-06 03:33 UTC, Prabhakar-Poudel commented on server/src/config/config.js
> +    JWT_SECRET: JWT_SECRET || 'MPCS',
What is 'MPCS' here? is it a secret for dev/test environments?

2019-05-06 03:33 UTC, Prabhakar-Poudel commented on server/src/controllers/auth.js
> +export const generateJWT = (userId) => {
This can be a util function.

2019-05-06 03:33 UTC, Prabhakar-Poudel commented on server/src/controllers/auth.js
> +  const token = jwt.sign({ id: userId }, JWT_SECRET); // TODO: add expiry time.
Please add expiry time to some time, we can update later. As such we don't have to change the interface later, only the value will be different.

2019-05-06 03:33 UTC, Prabhakar-Poudel commented on server/src/controllers/auth.js
>    return false;
For some reason false does not seem like correct response.
true -or> false is better
or in this case
id -or> null fits better

2019-05-06 03:33 UTC, Prabhakar-Poudel commented on server/src/controllers/auth.js
>  export const checkUser = async (userData) => {
can be named getUserId as this now returns user's id.

2019-05-06 03:33 UTC, Prabhakar-Poudel commented on server/src/controllers/auth.js
> +  const userId = await checkUser(userData);
What happens when checkUser does not return a user?

2019-05-06 03:33 UTC, Prabhakar-Poudel commented on server/src/index.js
> +  // TODO: have a separate route which uses token in header to get user data using User model.
This is not a clear comment. I did not understand what is to be done and why.

2019-05-14 14:37 UTC, closed without merging

2019-05-14 14:38 UTC, Prabhakar-Poudel commented
Handled by #74